spring:
  main:
    banner-mode: off
  profiles:
    active: dev 
  output:
    ansi:
      enabled: DETECT
  application:
    name: webflux-application
      
server:
  port: 9001
   
logging:
  level:
    org.springframework: ERROR
    com.webservice.webfluxdemo: DEBUG
    org.springframework.data.couchbase.repository.query: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
